name: Issue event test
on: 
    issues:
        types: [opened, edited, milestoned]
jobs:
    issue_test:
        runs-on: ubuntu-latest
        steps:
            - name: echo the issue 
              run: echo "${{ toJSON(github.event.issue) }}"